# Site settings
title: noxxdesigns
email: noxxadam@gmail.com
description: "I am a graphic designer."
baseurl: ""
url: "http://noxxdesigns.github.io"
author: "Equinoxx"

# Build settings
markdown: kramdown
permalink: pretty

# Add custom collections
collections:
  portfolio:
    output: true

# Set defaults
defaults:
  -
    scope:
      path: ""
      type: "page"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "post"
    values:
      layout: "post"    
      author: ""
      date: ""
      title: ""
      category: ""
      tags: ""
      